module.exports = {
  components: {
    categories: [
      {
        name: 'Components',
        include: [
          /* PLOP_INJECT_IMPORT */
          'src/components/Watermark/Watermark.jsx',
          'src/components/Upload/Upload.jsx',
          'src/components/Typography/Typography.jsx',
          // 'src/components/Typography/Text/Text.jsx',
          'src/components/TreeSelect/TreeSelect.jsx',
          'src/components/Tree/Tree.jsx',
          // 'src/components/Transfer/Transfer.jsx',
          'src/components/Tour/Tour.jsx',
          // 'src/components/Tooltip/Tooltip.jsx',
          'src/components/Timeline/Timeline.jsx',
          'src/components/TimePicker/TimePicker.jsx',
          'src/components/Tag/Tag.jsx',
          'src/components/Tabs/Tabs.jsx',
          // 'src/components/Table/Table.jsx',
          'src/components/Switch/Switch.jsx',
          'src/components/Steps/Steps.jsx',
          'src/components/Statistic/Statistic.jsx',
          'src/components/Spin/Spin.jsx',
          'src/components/Space/Space.jsx',
          'src/components/Slider/Slider.jsx',
          'src/components/Skeleton/Skeleton.jsx',
          'src/components/Select/Select.jsx',
          // 'src/components/Segmented/Segmented.jsx',
          'src/components/Row/Row.jsx',
          'src/components/Result/Result.jsx',
          'src/components/Rate/Rate.jsx',
          'src/components/Radio/Radio.jsx',
          'src/components/QrCode/QrCode.jsx',
          'src/components/Progress/Progress.jsx',
          'src/components/Popover/Popover.jsx',
          'src/components/Popconfirm/Popconfirm.jsx',
          'src/components/Pagination/Pagination.jsx',
          // 'src/components/Notification/Notification.jsx',
          'src/components/Modal/Modal.jsx',
          // 'src/components/Message/Message.jsx',
          'src/components/Menu/Menu.jsx',
          // 'src/components/Mentions/Mentions.jsx',
          // 'src/components/List/List.jsx',
          'src/components/Layout/Layout.jsx',
          'src/components/InputNumber/InputNumber.jsx',
          'src/components/Input/Input.jsx',
          'src/components/Image/Image.jsx',
          // 'src/components/Grid/Grid.jsx',
          'src/components/Form/Form.jsx',
          'src/components/FloatButton/FloatButton.jsx',
          'src/components/Flex/Flex.jsx',
          'src/components/Empty/Empty.jsx',
          'src/components/Dropdown/Dropdown.jsx',
          'src/components/Drawer/Drawer.jsx',
          'src/components/Divider/Divider.jsx',
          'src/components/Descriptions/Descriptions.jsx',
          // 'src/components/DatePicker/DatePicker.jsx',
          // 'src/components/ConfigProvider/ConfigProvider.jsx',
          'src/components/ColorPicker/ColorPicker.jsx',
          'src/components/Collapse/Collapse.jsx',
          'src/components/Col/Col.jsx',
          'src/components/Checkbox/Checkbox.jsx',
          // 'src/components/Cascader/Cascader.jsx',
          'src/components/Carousel/Carousel.jsx',
          'src/components/Card/Card.jsx',
          // 'src/components/Calendar/Calendar.jsx',
          'src/components/Button/Button.jsx',
          'src/components/Breadcrumb/Breadcrumb.jsx',
          'src/components/Badge/Badge.jsx',
          // 'src/components/BackTop/BackTop.jsx',
          'src/components/Avatar/Avatar.jsx',
          'src/components/AutoComplete/AutoComplete.jsx',
          'src/components/App/App.jsx',
          'src/components/Anchor/Anchor.jsx',
          'src/components/Alert/Alert.jsx',
          'src/components/Affix/Affix.jsx',
          // 'src/components/Mention/Mention.jsx',
          // 'src/components/LocaleProvider/LocaleProvider.jsx',
          // 'src/components/PageHeader/PageHeader.jsx',
          // 'src/components/Comment/Comment.jsx',
          // 'src/components/Provider/Provider.jsx',

        ],
      },
    ],
    wrapper: 'src/components/UXPinWrapper/UXPinWrapper.js',
    webpackConfig: 'webpack.config.js',
  },
  name: 'MUI-UXPin-Merge',
};
