module.exports = {
  components: {
    categories: [
      {
        name: 'Components',
        include: [
          /* PLOP_INJECT_IMPORT */
          'src/components/Button/Button.tsx',
          'src/components/Upload/Upload.tsx',
          'src/components/TreeSelect/TreeSelect.tsx',
          // 'src/components/Transfer/Transfer.tsx',
          'src/components/Pagination/Pagination.tsx',
          // 'src/components/Mention/Mention.tsx',
          // 'src/components/LocaleProvider/LocaleProvider.tsx',
          // 'src/components/ConfigProvider/ConfigProvider.tsx',
          'src/components/Anchor/Anchor.tsx',
          'src/components/Spin/Spin.tsx',
          'src/components/Result/Result.tsx',
          'src/components/Progress/Progress.tsx',
          'src/components/Popconfirm/Popconfirm.tsx',
          // 'src/components/Notification/Notification.tsx',
          'src/components/Modal/Modal.tsx',
          // 'src/components/Message/Message.tsx',
          'src/components/Drawer/Drawer.tsx',
          'src/components/Alert/Alert.tsx',
          'src/components/Steps/Steps.tsx',
          // 'src/components/PageHeader/PageHeader.tsx',
          'src/components/Menu/Menu.tsx',
          'src/components/Dropdown/Dropdown.tsx',
          'src/components/Breadcrumb/Breadcrumb.tsx',
          'src/components/BackTop/BackTop.tsx',
          'src/components/Affix/Affix.tsx',
          'src/components/Tree/Tree.tsx',
          // 'src/components/Tooltip/Tooltip.tsx',
          'src/components/Timeline/Timeline.tsx',
          'src/components/Tag/Tag.tsx',
          'src/components/Tabs/Tabs.tsx',
          // 'src/components/Table/Table.tsx',
          'src/components/Statistic/Statistic.tsx',
          'src/components/Popover/Popover.tsx',
          // 'src/components/List/List.tsx',
          'src/components/Empty/Empty.tsx',
          'src/components/Descriptions/Descriptions.tsx',
          // 'src/components/Comment/Comment.tsx',
          'src/components/Collapse/Collapse.tsx',
          'src/components/Carousel/Carousel.tsx',
          'src/components/Card/Card.tsx',
          // 'src/components/Calendar/Calendar.tsx',
          'src/components/Badge/Badge.tsx',
          'src/components/Avatar/Avatar.tsx',
          // 'src/components/DatePicker/DatePicker.tsx',
          'src/components/TimePicker/TimePicker.tsx',
          'src/components/Switch/Switch.tsx',
          'src/components/Select/Select.tsx',
          'src/components/Radio/Radio.tsx',
          'src/components/InputNumber/InputNumber.tsx',
          'src/components/Input/Input.tsx',
          'src/components/Form/Form.tsx',
          'src/components/Checkbox/Checkbox.tsx',
          // 'src/components/Provider/Provider.tsx',
          'src/components/Divider/Divider.tsx',
          // 'src/components/Cascader/Cascader.tsx',
          'src/components/AutoComplete/AutoComplete.tsx',
          'src/components/Layout/Layout.tsx',
          // 'src/components/Grid/Grid.tsx',

        ],
      },
    ],
    wrapper: 'src/components/UXPinWrapper/UXPinWrapper.tsx',
    webpackConfig: 'webpack.config.js',
  },
  name: 'MUI-UXPin-Merge',
};
